<?php

namespace Database\Seeders;

use App\Models\AdoptionRequest;
use App\Models\Animal;
use App\Models\Donation;
use App\Models\FoundRequest;
use App\Models\News;
use App\Models\Reward;
use App\Models\Task;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        Donation::query()->delete();
        News::query()->delete();
        AdoptionRequest::query()->delete();
        FoundRequest::query()->delete();
        Task::query()->delete();
        Animal::query()->delete();

        if (class_exists(Reward::class)) {
            Reward::query()->delete();
        }

        User::query()
            ->whereIn('email', [
                'admin@demo.ru',
                'volunteer@demo.ru',
                'maria@demo.ru',
                'amir@demo.ru',
            ])
            ->delete();

        User::create([
            'id' => 1,
            'name' => 'Админ',
            'email' => 'admin@demo.ru',
            'password' => Hash::make('admin'),
            'role' => 'admin',
            'points' => 0,
            'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop',
        ]);

        User::create([
            'id' => 2,
            'name' => 'Никита',
            'email' => 'volunteer@demo.ru',
            'password' => Hash::make('123456'),
            'role' => 'volunteer',
            'points' => 2184,
            'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop',
        ]);

        User::create([
            'id' => 3,
            'name' => 'Мария',
            'email' => 'maria@demo.ru',
            'password' => Hash::make('123456'),
            'role' => 'volunteer',
            'points' => 1760,
            'avatar' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop',
        ]);

        User::create([
            'id' => 4,
            'name' => 'Амир',
            'email' => 'amir@demo.ru',
            'password' => Hash::make('123456'),
            'role' => 'volunteer',
            'points' => 1390,
            'avatar' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop',
        ]);

        Animal::insert([
            [
                'id' => 11,
                'name' => 'Луна',
                'species' => 'Кошка',
                'age' => '1 год',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Ласковая и спокойная кошка, хорошо ладит с людьми.',
                'photo' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Барсик',
                'species' => 'Кот',
                'age' => '2 года',
                'city' => 'Москва',
                'status' => 'treatment',
                'description' => 'На лечении, нужен уход и спокойная передержка.',
                'photo' => 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Шарик',
                'species' => 'Пёс',
                'age' => '4 года',
                'city' => 'Химки',
                'status' => 'adopted',
                'description' => 'Добрый пёс, уже нашёл семью.',
                'photo' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Ричи',
                'species' => 'Пёс',
                'age' => '3 года',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Активный и умный пёс, любит прогулки и команды.',
                'photo' => 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Мила',
                'species' => 'Кошка',
                'age' => '8 месяцев',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Нежная кошечка, любит сидеть рядом и мурчать.',
                'photo' => 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Боня',
                'species' => 'Собака',
                'age' => '5 лет',
                'city' => 'Мытищи',
                'status' => 'treatment',
                'description' => 'Проходит восстановление после травмы.',
                'photo' => 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Соня',
                'species' => 'Кошка',
                'age' => '2 года',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Спокойная кошка для тихого дома.',
                'photo' => 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Тим',
                'species' => 'Пёс',
                'age' => '1.5 года',
                'city' => 'Королёв',
                'status' => 'looking_home',
                'description' => 'Дружелюбный молодой пёс, быстро учится.',
                'photo' => 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Нора',
                'species' => 'Кошка',
                'age' => '3 года',
                'city' => 'Москва',
                'status' => 'adopted',
                'description' => 'Уже дома, спасибо семье за заботу.',
                'photo' => 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Грей',
                'species' => 'Пёс',
                'age' => '6 лет',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Спокойный взрослый пёс, хорошо гуляет на поводке.',
                'photo' => 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Кнопа',
                'species' => 'Кошка',
                'age' => '5 месяцев',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Игривая малышка, ищет заботливую семью.',
                'photo' => 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Рекс',
                'species' => 'Собака',
                'age' => '4 года',
                'city' => 'Люберцы',
                'status' => 'treatment',
                'description' => 'Нуждается в регулярных осмотрах врача.',
                'photo' => 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Ася',
                'species' => 'Кошка',
                'age' => '1.5 года',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Любит людей, аккуратная и ласковая.',
                'photo' => 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Марс',
                'species' => 'Пёс',
                'age' => '2 года',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Весёлый компаньон для активной семьи.',
                'photo' => 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Тиша',
                'species' => 'Кот',
                'age' => '7 лет',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Очень тихий и домашний кот.',
                'photo' => 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Джек',
                'species' => 'Пёс',
                'age' => '1 год',
                'city' => 'Балашиха',
                'status' => 'looking_home',
                'description' => 'Молодой, активный, любит играть.',
                'photo' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Лея',
                'species' => 'Кошка',
                'age' => '4 года',
                'city' => 'Москва',
                'status' => 'adopted',
                'description' => 'Уже пристроена в добрые руки.',
                'photo' => 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Филя',
                'species' => 'Кот',
                'age' => '3 года',
                'city' => 'Москва',
                'status' => 'treatment',
                'description' => 'Восстанавливается, нужен мягкий уход.',
                'photo' => 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Буся',
                'species' => 'Собака',
                'age' => '2.5 года',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Дружит с детьми, любит прогулки.',
                'photo' => 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Персик',
                'species' => 'Кот',
                'age' => '2 года',
                'city' => 'Москва',
                'status' => 'looking_home',
                'description' => 'Рыжий ласковый кот, любит внимание.',
                'photo' => 'https://images.unsplash.com/photo-1571566882372-1598d88abd90?w=900&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Task::insert([
            [
                'title' => 'Купить корм',
                'description' => 'Купить 2 мешка сухого корма и доставить в приют.',
                'photo' => 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=900&h=650&fit=crop',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Отвезти Барсика к ветеринару',
                'description' => 'Нужно отвезти кота Барсика в клинику на плановый осмотр.',
                'photo' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Сфотографировать животных',
                'description' => 'Сделать новые фото для карточек животных на сайте.',
                'photo' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Помочь с уборкой вольеров',
                'description' => 'Нужна помощь с уборкой и подготовкой чистой подстилки.',
                'photo' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Доставить лекарства',
                'description' => 'Забрать лекарства из аптеки и передать куратору.',
                'photo' => 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&h=650&fit=crop',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Погулять с собаками',
                'description' => 'Помочь с вечерним выгулом собак на территории приюта.',
                'photo' => 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'status' => 'in_progress',
                'assigned_to' => 2,
                'points' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Разобрать склад помощи',
                'description' => 'Разложить корм, пледы и переноски по категориям.',
                'photo' => 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Обновить объявления',
                'description' => 'Разместить актуальные карточки животных в соцсетях.',
                'photo' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Помочь на дне открытых дверей',
                'description' => 'Встречать гостей, рассказывать о животных и правилах помощи.',
                'photo' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=900&h=650&fit=crop',
                'status' => 'open',
                'assigned_to' => null,
                'points' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Купить наполнитель',
                'description' => 'Купить наполнитель для кошек и доставить в приют.',
                'photo' => 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=900&h=650&fit=crop',
                'status' => 'done',
                'assigned_to' => 3,
                'points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        News::insert([
            [
                'title' => 'Новые поступления корма',
                'published_at' => now()->subDays(1),
                'text' => 'Спасибо всем, кто помог закрыть сбор на корм для животных.',
                'image' => 'https://images.unsplash.com/photo-1601758123927-196434e016d1?w=1000&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Луна ищет дом',
                'published_at' => now()->subDays(2),
                'text' => 'Ласковая кошка Луна готова к переезду в новую семью.',
                'image' => 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'День открытых дверей',
                'published_at' => now()->subDays(3),
                'text' => 'Приглашаем всех познакомиться с животными и волонтёрами.',
                'image' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1000&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Сбор на лечение Рекса',
                'published_at' => now()->subDays(4),
                'text' => 'Псу Рексу требуется дополнительное обследование, лечение и лекарства.',
                'image' => 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Нужны волонтёры на выходные',
                'published_at' => now()->subDays(5),
                'text' => 'В эти выходные особенно нужна помощь с выгулом и уборкой.',
                'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'История счастливого пристройства',
                'published_at' => now()->subDays(6),
                'text' => 'Шарик уехал домой и уже осваивается в новой семье.',
                'image' => 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=1200&h=800&fit=crop&crop=faces&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Партнёры передали подарки',
                'published_at' => now()->subDays(7),
                'text' => 'Наши партнёры передали сертификаты и полезные товары для волонтёров.',
                'image' => 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Обновили карточки животных',
                'published_at' => now()->subDays(8),
                'text' => 'На сайте появились новые фото и описания питомцев.',
                'image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Спасибо волонтёрам месяца',
                'published_at' => now()->subDays(9),
                'text' => 'Отмечаем самых активных волонтёров и благодарим за помощь.',
                'image' => 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Нужны переноски для кошек',
                'published_at' => now()->subDays(10),
                'text' => 'Приюту нужны переноски для поездок в ветеринарные клиники.',
                'image' => 'https://images.unsplash.com/photo-1570824104453-508955ab713e?w=1000&h=650&fit=crop',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Donation::insert([
            [
                'goal' => 50000,
                'raised' => 17500,
                'text' => 'Сбор на лечение и корм',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'goal' => 30000,
                'raised' => 12000,
                'text' => 'Сбор на лекарства для животных',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'goal' => 45000,
                'raised' => 45000,
                'text' => 'Сбор на ремонт вольеров',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        FoundRequest::create([
            'id' => 201,
            'city' => 'Москва',
            'address' => 'ул. Ленина 10',
            'description' => 'Кот серый, хромает',
            'status' => 'new',
        ]);

        AdoptionRequest::create([
            'id' => 301,
            'animal_name' => 'Луна',
            'name' => 'Иван',
            'phone' => '+7...',
            'message' => 'Готов взять на передержку',
            'status' => 'new',
        ]);

        if (class_exists(Reward::class)) {
            Reward::insert([
                [
                    'title' => 'Сертификат в зоомагазин',
                    'partner_name' => 'ZooMarket',
                    'description' => 'Сертификат на покупку товаров для питомцев.',
                    'image' => 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=900&h=650&fit=crop',
                    'price_points' => 300,
                    'stock' => 8,
                    'category' => 'certificates',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Кофе от партнёра',
                    'partner_name' => 'Coffee Point',
                    'description' => 'Бесплатный кофе для активных волонтёров.',
                    'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&h=650&fit=crop',
                    'price_points' => 120,
                    'stock' => 20,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Футболка волонтёра',
                    'partner_name' => 'Shelter Merch',
                    'description' => 'Фирменная футболка волонтёра приюта.',
                    'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&h=650&fit=crop',
                    'price_points' => 450,
                    'stock' => 12,
                    'category' => 'merch',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Скидка на груминг',
                    'partner_name' => 'Pet Beauty',
                    'description' => 'Скидка 30% на груминг для питомца.',
                    'image' => 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=900&h=650&fit=crop',
                    'price_points' => 250,
                    'stock' => 10,
                    'category' => 'discounts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Бутылка для воды',
                    'partner_name' => 'EcoLife',
                    'description' => 'Многоразовая бутылка для прогулок и выездов.',
                    'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900&h=650&fit=crop',
                    'price_points' => 180,
                    'stock' => 15,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Худи приюта',
                    'partner_name' => 'Shelter Merch',
                    'description' => 'Тёплое худи с логотипом приюта.',
                    'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=900&h=650&fit=crop',
                    'price_points' => 700,
                    'stock' => 6,
                    'category' => 'merch',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Плед для дома',
                    'partner_name' => 'HomeWarm',
                    'description' => 'Мягкий плед от партнёров проекта.',
                    'image' => 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&h=650&fit=crop',
                    'price_points' => 380,
                    'stock' => 9,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Скидка в ветклинику',
                    'partner_name' => 'VetPlus',
                    'description' => 'Скидка на первичный приём в ветеринарной клинике.',
                    'image' => 'https://images.unsplash.com/photo-1576765607924-420b6aa1dfc1?w=900&h=650&fit=crop',
                    'price_points' => 320,
                    'stock' => 10,
                    'category' => 'discounts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Подарочный набор',
                    'partner_name' => 'GoodBox',
                    'description' => 'Набор полезных мелочей для волонтёра.',
                    'image' => 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=900&h=650&fit=crop',
                    'price_points' => 260,
                    'stock' => 14,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Книга о животных',
                    'partner_name' => 'BookFriend',
                    'description' => 'Полезная книга о поведении домашних животных.',
                    'image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=900&h=650&fit=crop',
                    'price_points' => 220,
                    'stock' => 11,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Сертификат на доставку',
                    'partner_name' => 'CityDelivery',
                    'description' => 'Сертификат на бесплатную доставку по городу.',
                    'image' => 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=900&h=650&fit=crop',
                    'price_points' => 200,
                    'stock' => 15,
                    'category' => 'certificates',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Термокружка',
                    'partner_name' => 'Coffee Point',
                    'description' => 'Удобная термокружка для выездов и прогулок.',
                    'image' => 'https://images.unsplash.com/photo-1517701550927-30cf4ba1f4d6?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                    'price_points' => 280,
                    'stock' => 13,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Шоппер приюта',
                    'partner_name' => 'Shelter Merch',
                    'description' => 'Тканевая сумка с символикой приюта.',
                    'image' => 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=1200&h=800&fit=crop&crop=entropy&auto=format&q=90',
                    'price_points' => 160,
                    'stock' => 25,
                    'category' => 'merch',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Скидка на корм',
                    'partner_name' => 'ZooMarket',
                    'description' => 'Скидка 20% на корм для домашних питомцев.',
                    'image' => 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=900&h=650&fit=crop',
                    'price_points' => 240,
                    'stock' => 18,
                    'category' => 'discounts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Блокнот волонтёра',
                    'partner_name' => 'PaperLab',
                    'description' => 'Блокнот для заметок и планирования задач.',
                    'image' => 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=900&h=650&fit=crop',
                    'price_points' => 110,
                    'stock' => 30,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Сертификат на фотосессию',
                    'partner_name' => 'PhotoPet',
                    'description' => 'Мини-фотосессия с питомцем от партнёра.',
                    'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&h=650&fit=crop',
                    'price_points' => 650,
                    'stock' => 4,
                    'category' => 'certificates',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Набор стикеров',
                    'partner_name' => 'Shelter Merch',
                    'description' => 'Стикеры с животными приюта.',
                    'image' => 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=900&h=650&fit=crop',
                    'price_points' => 80,
                    'stock' => 40,
                    'category' => 'merch',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Эко-набор',
                    'partner_name' => 'EcoLife',
                    'description' => 'Многоразовые аксессуары для повседневного использования.',
                    'image' => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=900&h=650&fit=crop',
                    'price_points' => 340,
                    'stock' => 8,
                    'category' => 'gifts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Скидка на обучение',
                    'partner_name' => 'PetSchool',
                    'description' => 'Скидка на курс по уходу за животными.',
                    'image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900&h=650&fit=crop',
                    'price_points' => 500,
                    'stock' => 7,
                    'category' => 'discounts',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Подарочная карта',
                    'partner_name' => 'Partner Club',
                    'description' => 'Подарочная карта от партнёров приюта.',
                    'image' => 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=900&h=650&fit=crop',
                    'price_points' => 600,
                    'stock' => 5,
                    'category' => 'certificates',
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
    }
}